package com.springfield.website.common;

public enum ParamKey {

    DEFAULT_BUSINESS_LOAN_APPLICATION_TENURE,
    BUSINESS_LOAN_APPLICATION_INTEREST,
    DEFAULT_BUSINESS_LOAN_APPLICATION_INTEREST_INCREMENT,
    ADMIN_RECIPIENT_MAILS
}
