package com.springfield.website.modules.loan.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum BusinessType {
    SOLE_PROPRIETORSHIP("Sole Proprietorship"),
    PARTNERSHIP("Partnership"),
    LIMITED_PARTNERSHIP("Limited Partnership"),
    CORPORATION("Corporation"),
    LIMITED_LIABILITY_COMPANY("Limited Liability Company (LLC)"),
    NON_PROFIT_ORGANIZATION("Non-Profit Organization"),
    COOPERATIVE("Cooperative"),
    FRANCHISE("Franchise"),
    JOINT_VENTURE("Joint Venture"),
    TRUST("Trust"),
    PUBLIC_CORPORATION("Public Corporation"),
    PRIVATE_CORPORATION("Private Corporation"),
    HOLDING_COMPANY("Holding Company"),
    SUBSIDIARY("Subsidiary"),
    SOCIAL_ENTERPRISE("Social Enterprise"),
    STARTUP("Startup"),
    FREELANCE("Freelance"),
    CONSULTANCY("Consultancy"),
    ONLINE_BUSINESS("Online Business"),
    MANUFACTURING_BUSINESS("Manufacturing Business"),
    RETAIL_BUSINESS("Retail Business"),
    WHOLESALE_BUSINESS("Wholesale Business"),
    SERVICE_BUSINESS("Service Business"),
    AGRICULTURE_BUSINESS("Agriculture Business"),
    REAL_ESTATE_BUSINESS("Real Estate Business"),
    TECHNOLOGY_BUSINESS("Technology Business"),
    HEALTHCARE_BUSINESS("Healthcare Business"),
    EDUCATION_BUSINESS("Education Business"),
    TRANSPORTATION_BUSINESS("Transportation Business"),
    HOSPITALITY_BUSINESS("Hospitality Business"),
    ENERGY_BUSINESS("Energy Business"),
    FINANCIAL_SERVICES("Financial Services"),
    MEDIA_AND_ENTERTAINMENT("Media and Entertainment"),
    CONSTRUCTION_BUSINESS("Construction Business"),
    TOURISM_BUSINESS("Tourism Business"),
    FOOD_AND_BEVERAGE("Food and Beverage"),
    EVENT_MANAGEMENT("Event Management"),
    ARTS_AND_CRAFTS("Arts and Crafts"),
    IMPORT_EXPORT_BUSINESS("Import Export Business"),
    E_COMMERCE_BUSINESS("E-Commerce Business"),
    LOGISTICS_AND_SUPPLY_CHAIN("Logistics and Supply Chain"),
    AUTOMOTIVE_BUSINESS("Automotive Business"),
    PHARMACEUTICAL_BUSINESS("Pharmaceutical Business"),
    FASHION_AND_APPAREL("Fashion and Apparel"),
    MARKETING_AND_ADVERTISING("Marketing and Advertising"),
    TELECOMMUNICATIONS_BUSINESS("Telecommunications Business"),
    SOFTWARE_DEVELOPMENT("Software Development"),
    GAME_DEVELOPMENT("Game Development"),
    DATA_ANALYTICS("Data Analytics"),
    CYBERSECURITY_BUSINESS("Cybersecurity Business"),
    BLOCKCHAIN_BUSINESS("Blockchain Business"),
    AI_AND_MACHINE_LEARNING("AI and Machine Learning"),
    BIOTECHNOLOGY_BUSINESS("Biotechnology Business"),
    ENVIRONMENTAL_SERVICES("Environmental Services"),
    LEGAL_SERVICES("Legal Services"),
    ACCOUNTING_AND_AUDIT("Accounting and Audit"),
    ARCHITECTURE_AND_ENGINEERING("Architecture and Engineering"),
    PRINTING_AND_PUBLISHING("Printing and Publishing"),
    HOME_SERVICES("Home Services"),
    BEAUTY_AND_WELLNESS("Beauty and Wellness"),
    SPORTS_AND_FITNESS("Sports and Fitness"),
    MINING_AND_EXTRACTION("Mining and Extraction"),
    PETROLEUM_AND_GAS("Petroleum and Gas"),
    AEROSPACE_BUSINESS("Aerospace Business"),
    RESEARCH_AND_DEVELOPMENT("Research and Development"),
    CLEANING_SERVICES("Cleaning Services"),
    CHILDCARE_SERVICES("Childcare Services"),
    PET_SERVICES("Pet Services"),
    ANTIQUE_BUSINESS("Antique Business"),
    CULTURAL_BUSINESS("Cultural Business"),
    LUXURY_BUSINESS("Luxury Business"),
    SECURITY_SERVICES("Security Services"),
    TRANSLATION_SERVICES("Translation Services"),
    RENTAL_SERVICES("Rental Services"),
    GREEN_TECH_BUSINESS("Green Tech Business"),
    EDUTAINMENT("Edutainment"),
    MICROFINANCE_BUSINESS("Microfinance Business"),
    CROWDFUNDING_BUSINESS("Crowdfunding Business"),
    VIRTUAL_ASSISTANT_SERVICES("Virtual Assistant Services"),
    HEMP_AND_CANNABIS_BUSINESS("Hemp and Cannabis Business"),
    SPACE_TECHNOLOGY("Space Technology"),
    DRONES_AND_AUTOMATION("Drones and Automation"),
    CLOUD_COMPUTING_BUSINESS("Cloud Computing Business"),
    HEALTH_AND_WELLNESS_TECH("Health and Wellness Tech"),
    RENEWABLE_ENERGY_BUSINESS("Renewable Energy Business"),
    SHIPPING_AND_PORT_SERVICES("Shipping and Port Services"),
    FREELANCE_SERVICES("Freelance Services"),
    CONSULTANCY_BUSINESS("Consultancy Business"),
    PUBLIC_RELATIONS("Public Relations"),
    AGRICULTURE_AND_FARMING("Agriculture and Farming"),
    FISHERY_BUSINESS("Fishery Business"),
    FORESTRY_BUSINESS("Forestry Business"),
    PROPERTY_MANAGEMENT("Property Management"),
    INTERIOR_DESIGN("Interior Design"),
    EVENT_PLANNING("Event Planning"),
    CATERING_BUSINESS("Catering Business"),
    BAKING_AND_CONFECTIONERY("Baking and Confectionery"),
    FOOD_TRUCK_BUSINESS("Food Truck Business"),
    EDUCATION_AND_TRAINING("Education and Training"),
    TUTORING_SERVICES("Tutoring Services"),
    TECH_SUPPORT_SERVICES("Tech Support Services"),
    GRAPHIC_DESIGN("Graphic Design"),
    WEB_DEVELOPMENT("Web Development"),
    PHOTOGRAPHY_BUSINESS("Photography Business"),
    VIDEOGRAPHY_BUSINESS("Videography Business"),
    SOCIAL_MEDIA_MANAGEMENT("Social Media Management"),
    SEARCH_ENGINE_OPTIMIZATION("Search Engine Optimization"),
    CONTENT_WRITING("Content Writing"),
    BOOKKEEPING_SERVICES("Bookkeeping Services"),
    FINANCIAL_ADVISORY("Financial Advisory"),
    INSURANCE_SERVICES("Insurance Services"),
    TRAVEL_AGENCY("Travel Agency"),
    CAR_RENTAL_SERVICES("Car Rental Services"),
    TRANSPORTATION_SERVICES("Transportation Services"),
    WAREHOUSING_AND_STORAGE("Warehousing and Storage"),
    TEXTILE_AND_FABRIC_BUSINESS("Textile and Fabric Business"),
    PLUMBING_SERVICES("Plumbing Services"),
    ELECTRICAL_SERVICES("Electrical Services"),
    HVAC_SERVICES("HVAC Services"),
    LANDSCAPING_SERVICES("Landscaping Services"),
    TREE_SURGERY_SERVICES("Tree Surgery Services"),
    WASTE_MANAGEMENT("Waste Management"),
    RECYCLING_BUSINESS("Recycling Business"),
    TATTOO_AND_PIERCING_SERVICES("Tattoo and Piercing Services"),
    MOBILE_APP_DEVELOPMENT("Mobile App Development"),
    VIRTUAL_REALITY_BUSINESS("Virtual Reality Business"),
    AUGMENTED_REALITY_BUSINESS("Augmented Reality Business"),
    NFT_BUSINESS("NFT Business"),
    DIGITAL_MARKETPLACE("Digital Marketplace"),
    SUBSCRIPTION_SERVICES("Subscription Services"),
    CHARITY_AND_NON_PROFIT("Charity and Non-Profit"),
    TRADE_SHOW_ORGANIZATION("Trade Show Organization"),
    BUSINESS_INCUBATOR("Business Incubator"),
    COWORKING_SPACE("Coworking Space"),
    FRANCHISING_BUSINESS("Franchising Business"),
    AUCTION_SERVICES("Auction Services"),
    CUSTOMER_SERVICE_OUTSOURCING("Customer Service Outsourcing"),
    CALL_CENTER_SERVICES("Call Center Services"),
    CLOUD_STORAGE_BUSINESS("Cloud Storage Business"),
    IT_MANAGED_SERVICES("IT Managed Services"),
    BPO_SERVICES("BPO Services"),
    PERSONAL_TRAINING("Personal Training"),
    YOGA_AND_MEDITATION_STUDIO("Yoga and Meditation Studio"),
    FITNESS_EQUIPMENT_BUSINESS("Fitness Equipment Business"),
    WATER_PARK_AND_AMUSEMENT_PARK("Water Park and Amusement Park"),
    CASINO_BUSINESS("Casino Business"),
    ENTERTAINMENT_PRODUCTION("Entertainment Production"),
    FILM_AND_TV_STUDIOS("Film and TV Studios"),
    MUSIC_PRODUCTION_BUSINESS("Music Production Business"),
    EVENT_DECORATION("Event Decoration"),
    REPAIR_AND_MAINTENANCE_SERVICES("Repair and Maintenance Services"),
    FUEL_STATION_BUSINESS("Fuel Station Business"),
    HOME_AUTOMATION_SERVICES("Home Automation Services"),
    PERSONAL_CARE_SERVICES("Personal Care Services"),
    GARDENING_SERVICES("Gardening Services"),
    HOBBY_AND_LEISURE_BUSINESS("Hobby and Leisure Business"),
    OFFICE_SUPPLY_BUSINESS("Office Supply Business"),
    PACKAGING_AND_LABELLING("Packaging and Labelling"),
    TESTING_AND_INSPECTION_SERVICES("Testing and Inspection Services"),
    QUALITY_ASSURANCE_SERVICES("Quality Assurance Services"),
    DOCUMENT_DIGITIZATION("Document Digitization"),
    LEGAL_TRANSCRIPTION("Legal Transcription"),
    MEDICAL_TRANSCRIPTION("Medical Transcription"),
    PEST_CONTROL_SERVICES("Pest Control Services"),
    CAR_WASH_BUSINESS("Car Wash Business"),
    ANTIQUES_AND_COLLECTIBLES("Antiques and Collectibles"),
    PETROL_CHEMICAL_BUSINESS("Petrol Chemical Business"),
    FURNITURE_MANUFACTURING("Furniture Manufacturing"),
    LEATHER_GOODS_BUSINESS("Leather Goods Business");

    private final String description;
}
