package com.springfield.website.modules.loan.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum BusinessLocation {

    LAGOS("Lagos"),
    ABUJA("Abuja"),
    PORT_HARCOURT("Port Harcourt"),
    KANO("Kano"),
    IBADAN("Ibadan"),
    BENIN_CITY("Benin City"),
    ENUGU("Enugu"),
    CALABAR("Calabar"),
    MAIDUGURI("Maiduguri"),
    OWERRI("Owerri"),
    ONITSHA("Onitsha"),
    ABA("Aba"),
    WARRI("Warri"),
    JOS("Jos"),
    SOKOTO("Sokoto"),
    KADUNA("Kaduna"),
    ILORIN("Ilorin"),
    ASABA("Asaba"),
    YOLA("Yola"),
    UYO("Uyo"),
    MINNA("Minna"),
    LOKOJA("Lokoja"),
    MAKURDI("Makurdi"),
    EKET("Eket"),
    IKEJA("Ikeja"),
    IKORODU("Ikorodu"),
    OSHOGBO("Oshogbo"),
    ADO_EKITI("Ado-Ekiti"),
    AKURE("Akure"),
    OGBOMOSHO("Ogbomosho"),
    OGIDI("Ogidi"),
    IKOT_EKPENE("Ikot Ekpene"),
    BAUCHI("Bauchi"),
    GOMBE("Gombe"),
    DAMATURU("Damaturu"),
    KATSINA("Katsina"),
    GUSAU("Gusau"),
    BIRNIN_KEBBI("Birnin Kebbi"),
    AWKA("Awka"),
    UMUAHIA("Umuahia"),
    AWGU("Awgu"),
    OTUKPO("Otukpo"),
    GBOKO("Gboko"),
    IJEBU_ODE("Ijebu-Ode"),
    ABEOKUTA("Abeokuta"),
    EFFURUN("Effurun"),
    UGHELLI("Ughelli"),
    JALINGO("Jalingo"),
    CALABAR_SOUTH("Calabar South"),
    OYO("Oyo"),
    EKPOMA("Ekpoma"),
    OBIARUKU("Obiaruku"),
    BIRNIN_GWARI("Birnin Gwari"),
    KAFANCHAN("Kafanchan"),
    ZARIA("Zaria"),
    KEFFI("Keffi"),
    FUNTUA("Funtua"),
    KAINJI("Kainji"),
    BADAGRY("Badagry"),
    VICTORIA_ISLAND("Victoria Island"),
    LEKKI("Lekki"),
    AJAH("Ajah"),
    APAPA("Apapa"),
    IJORA("Ijora"),
    MARINA("Marina"),
    IKEJA_GRA("Ikeja GRA"),
    SURULERE("Surulere"),
    FESTAC("Festac"),
    SHOMOLU("Shomolu"),
    YABA("Yaba");

    private final String description;
}
