package com.springfield.website.modules.loan.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum CollateralType {

    REAL_ESTATE("Real Estate"),
    RESIDENTIAL_PROPERTY("Residential Property"),
    COMMERCIAL_PROPERTY("Commercial Property"),
    LAND("Land"),
    FARM_LAND("Farm Land"),
    INDUSTRIAL_PROPERTY("Industrial Property"),
    VEHICLES("Vehicles"),
    CARS("Cars"),
    TRUCKS("Trucks"),
    MOTORCYCLES("Motorcycles"),
    AIRCRAFT("Aircraft"),
    SHIPS_AND_BOATS("Ships and Boats"),
    EQUIPMENT("Equipment"),
    HEAVY_MACHINERY("Heavy Machinery"),
    OFFICE_EQUIPMENT("Office Equipment"),
    MEDICAL_EQUIPMENT("Medical Equipment"),
    IT_EQUIPMENT("IT Equipment"),
    INVENTORY("Inventory"),
    STOCK("Stock"),
    RAW_MATERIALS("Raw Materials"),
    FINISHED_GOODS("Finished Goods"),
    ACCOUNTS_RECEIVABLE("Accounts Receivable"),
    BANK_DEPOSITS("Bank Deposits"),
    FIXED_DEPOSITS("Fixed Deposits"),
    GOVERNMENT_SECURITIES("Government Securities"),
    BONDS("Bonds"),
    SHARES("Shares"),
    MUTUAL_FUNDS("Mutual Funds"),
    PRECIOUS_METALS("Precious Metals"),
    GOLD("Gold"),
    SILVER("Silver"),
    PLATINUM("Platinum"),
    JEWELRY("Jewelry"),
    LIVESTOCK("Livestock"),
    CROPS("Crops"),
    INSURANCE_POLICIES("Insurance Policies"),
    TRADEMARKS("Trademarks"),
    PATENTS("Patents"),
    COPYRIGHTS("Copyrights"),
    LICENSING_AGREEMENTS("Licensing Agreements"),
    FRANCHISE_RIGHTS("Franchise Rights"),
    ENERGY_CREDITS("Energy Credits"),
    RENTAL_INCOME("Rental Income"),
    ROYALTY_INCOME("Royalty Income"),
    PROMISSORY_NOTES("Promissory Notes"),
    GUARANTEES("Guarantees"),
    SECURITY_DEPOSITS("Security Deposits"),
    PERSONAL_ASSETS("Personal Assets"),
    FURNITURE("Furniture"),
    ARTWORK("Artwork"),
    COLLECTIBLES("Collectibles"),
    PRECIOUS_STONES("Precious Stones"),
    CRYPTOCURRENCY("Cryptocurrency"),
    BITCOIN("Bitcoin"),
    ETHEREUM("Ethereum"),
    OTHER_DIGITAL_ASSETS("Other Digital Assets"),
    AGRICULTURAL_LAND("Agricultural Land"),
    WAREHOUSES("Warehouses"),
    COMMERCIAL_UNITS("Commercial Units"),
    MINERAL_RESOURCES("Mineral Resources"),
    OIL_RESERVES("Oil Reserves"),
    NATURAL_GAS("Natural Gas"),
    TIMBER("Timber"),
    FISHING_RIGHTS("Fishing Rights"),
    WATER_RIGHTS("Water Rights"),
    TRADE_FINANCE_INSTRUMENTS("Trade Finance Instruments"),
    LETTER_OF_CREDIT("Letter of Credit"),
    BILL_OF_LADING("Bill of Lading"),
    CONSTRUCTION_MATERIALS("Construction Materials"),
    INTANGIBLE_ASSETS("Intangible Assets"),
    CLIENT_CONTRACTS("Client Contracts"),
    BUSINESS_LICENSES("Business Licenses"),
    UTILITY_ASSETS("Utility Assets"),
    RAILWAY_EQUIPMENT("Railway Equipment"),
    TELECOMMUNICATIONS_EQUIPMENT("Telecommunications Equipment"),
    SOLAR_PANELS("Solar Panels"),
    WIND_TURBINES("Wind Turbines"),
    HYDRO_POWER_ASSETS("Hydro Power Assets"),
    FOREIGN_CURRENCY("Foreign Currency"),
    CREDIT_CARD_RECEIVABLES("Credit Card Receivables"),
    SUPPLY_CONTRACTS("Supply Contracts"),
    PARTNERSHIP_INTERESTS("Partnership Interests"),
    FRACTIONAL_REAL_ESTATE("Fractional Real Estate"),
    TIMESHARES("Timeshares"),
    COMMUNITY_ASSETS("Community Assets"),
    TANGIBLE_FIXED_ASSETS("Tangible Fixed Assets"),
    IN_KIND_DONATIONS("In-Kind Donations"),
    PARTIAL_INTERESTS("Partial Interests"),
    UTILITY_BONDS("Utility Bonds"),
    MUNICIPAL_BONDS("Municipal Bonds"),
    CEMETERY_PLOTS("Cemetery Plots"),
    RARE_EARTH_ELEMENTS("Rare Earth Elements"),
    GAS_STATIONS("Gas Stations"),
    HOTELS("Hotels"),
    RESORTS("Resorts"),
    AIRLINE_SLOTS("Airline Slots"),
    MARINA_SLIPS("Marina Slips"),
    FILM_ROYALTIES("Film Royalties"),
    MUSIC_ROYALTIES("Music Royalties"),
    BOOK_ROYALTIES("Book Royalties"),
    PUBLISHING_RIGHTS("Publishing Rights"),
    REPUTATION_CREDIT("Reputation Credit"),
    MARKETING_ASSETS("Marketing Assets"),
    FRANCHISE_FEES("Franchise Fees"),
    SUBSCRIPTION_RECEIVABLES("Subscription Receivables"),
    WORK_IN_PROGRESS("Work in Progress"),
    EMPLOYEE_BENEFIT_FUNDS("Employee Benefit Funds"),
    HEDGE_FUND_ASSETS("Hedge Fund Assets"),
    PRIVATE_EQUITY("Private Equity"),
    TRUST_FUND_INTERESTS("Trust Fund Interests"),
    MARITIME_LIENS("Maritime Liens"),
    RENEWABLE_ENERGY_ASSETS("Renewable Energy Assets"),
    GEOTHERMAL_RESOURCES("Geothermal Resources"),
    RECYCLING_EQUIPMENT("Recycling Equipment"),
    PLASTIC_CREDITS("Plastic Credits"),
    CARBON_OFFSETS("Carbon Offsets"),
    LAND_RECLAMATION_RIGHTS("Land Reclamation Rights"),
    CROWDFUNDED_ASSETS("Crowdfunded Assets"),
    LEASED_EQUIPMENT("Leased Equipment"),
    SUBLEASES("Subleases"),
    VENDOR_FINANCING("Vendor Financing"),
    FUTURES_CONTRACTS("Futures Contracts"),
    OPTIONS_CONTRACTS("Options Contracts"),
    DERIVATIVES("Derivatives"),
    COMMUNITY_DEVELOPMENT_LOANS("Community Development Loans"),
    RENEWABLE_ENERGY_CREDITS("Renewable Energy Credits"),
    POLLUTION_PERMITS("Pollution Permits"),
    UTILITY_BILL_RECEIVABLES("Utility Bill Receivables"),
    INTERNATIONAL_BONDS("International Bonds"),
    SPORTS_FRANCHISES("Sports Franchises"),
    GAMING_LICENSES("Gaming Licenses"),
    SMALL_BUSINESS_LOANS("Small Business Loans");

    private final String description;
}
